docs_dir: docs/zh
site_name: x-studio
repo_url: https://github.com/simdsoft/x-studio
repo_name: GitHub
edit_uri: edit/master/docs/zh
copyright: Copyright &copy; 2014 - 2021 Simdsoft Limited.
theme:
  name: material
  language: zh
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
nav:
  - 主页: index.md
  - 代码编辑篇: coding/index.md
  - Lua调试: 
    - 前言: lua-dbg/index.md
    - Unity3D Lua调试: lua-dbg/01_unity3d.md
    - Cocos2d-x Lua调试: lua-dbg/02_cclua.md
    - 标准Lua调试: lua-dbg/03_olua.md
    - 常见问题: lua-dbg/04_faq.md
  - UI编辑: 
    - CSD恢复: ui-editing/02_csd-recov.md
    - 常见问题: ui-editing/03_faq.md
  - 高级:
    - 加密解决方案: advanced/01_encrypt.md
    - 软件升级: advanced/02_upgrade.md
  - 使用技巧: use-skills.md
  - 软件快捷键: shortcuts.md
  - 软件设置: settings.md
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: simdsoft
      repo: x-studio
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\，\。]+'
  - pdf-export:
      verbose: false
      media_type: print
      combined: true
      combined_output_path: pdf/yasio-latest.pdf
      enabled_if_env: DOCS_CI
  - minify:
      minify_html: true
extra_css:
  - 'assets/stylesheets/extra.css'
